# Generated by Django 3.2.13 on 2022-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gps_lat',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='gps_lng',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=15),
        ),
    ]
