# Generated by Django 3.2.13 on 2022-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20220420_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gps_lat',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gps_lng',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=7),
        ),
    ]
